spring:
  application:
    name: "profile"
  data:
    mongodb:
      host: mongo-server
      port: 27017
      username: admin
      password: secret
      database: ms-customer
      authentication-database: admin

server:
  port: 8071